import type {
  Award,
  BlogPost,
  Certificate,
  Education,
  Experience,
  LanguageItem,
  Project,
  ResearchItem,
  SiteProfile,
  Skill,
} from '@/types/content'

export const siteProfile: SiteProfile = {
  brand: 'Portfolio',
  fullName: 'Ngô Ngọc Triệu Mẫn',
  role: {
    en: 'Game Developer',
    vi: 'Lập trình viên Game',
  },
  tagline: {
    en: 'Beauty catches the eye. A sharper mind builds what lasts.',
    vi: 'Vẻ đẹp thu hút ánh nhìn. Một tư duy sắc bén tạo nên giá trị bền lâu.',
  },
  about: {
    en: 'I build interactive experiences with Unity, game systems, AR/VR and thoughtful product design. I enjoy turning technical ideas into experiences that feel clear, playful and useful.',
    vi: 'Mình xây dựng các trải nghiệm tương tác bằng Unity, hệ thống gameplay, AR/VR và tư duy thiết kế sản phẩm. Mình thích biến những ý tưởng kỹ thuật thành trải nghiệm rõ ràng, thú vị và hữu ích.',
  },
  city: { en: 'Ho Chi Minh City, Vietnam', vi: 'TP. Hồ Chí Minh, Việt Nam' },
  email: 'man.ngoman2705@gmail.com',
  phone: '0865127514',
  github: 'https://github.com/Kandy2705',
  linkedin: 'https://www.linkedin.com/in/m%E1%BA%ABn-ng%C3%B4-ng%E1%BB%8Dc-tri%E1%BB%87u-86b199362/',
  facebook: 'https://www.facebook.com/phuong.nghi.trieu.man/',
  profileImageUrl: '/images/profile/profile.jpg',
  cvEnUrl: '/cv/game-developer-en.html',
  cvViUrl: '/cv/game-developer-vi.html',
  cvWebViUrl: '/cv/web-developer-vi.html',
}

export const projects: Project[] = [
  {
    id: 'agentic-ar',
    slug: 'agentic-ar',
    title: 'Agentic AR',
    excerpt: {
      en: 'An AR navigation application for finding campus buildings and classrooms using GPS positioning and AR overlays.',
      vi: 'Ứng dụng dẫn đường AR giúp sinh viên tìm tòa nhà và lớp học bằng định vị GPS kết hợp lớp phủ AR.',
    },
    content: {
      en: `## Overview\nAgentic AR explores seamless navigation between outdoor GPS guidance and indoor spatial guidance.\n\n## What I worked on\n- Designed high-fidelity UI/UX in Figma and implemented the interface in Unity.\n- Researched WGS84-to-Unity coordinate conversion.\n- Built route-management logic with C# and AR Foundation.\n- Managed project milestones and source control.\n\n## Direction\nThe project is being developed toward research publication in **Computers & Graphics (Elsevier)**.`,
      vi: `## Tổng quan\nAgentic AR nghiên cứu trải nghiệm dẫn đường liền mạch giữa định vị GPS ngoài trời và định hướng không gian trong nhà.\n\n## Phần mình phụ trách\n- Thiết kế UI/UX trên Figma và triển khai giao diện trong Unity.\n- Nghiên cứu chuyển đổi tọa độ WGS84 sang không gian Unity.\n- Xây dựng logic quản lý route bằng C# và AR Foundation.\n- Quản lý tiến độ dự án và source control.\n\n## Định hướng\nDự án đang được phát triển theo hướng bài báo nghiên cứu tại **Computers & Graphics (Elsevier)**.`,
    },
    categories: ['AR/VR', 'Research'],
    technologies: ['Unity', 'C#', 'AR Foundation', 'GPS', 'AI Navigation', 'Supabase', 'Figma'],
    role: { en: 'Lead & Developer', vi: 'Lead & Developer' },
    startDate: '2025-07-01',
    endDate: null,
    teamSize: 3,
    status: { en: 'In progress', vi: 'Đang phát triển' },
    githubUrl: 'https://github.com/Kandy2705/AR-Navigation-BK',
    demoUrl: null,
    appStoreUrl: null,
    playStoreUrl: null,
    videoUrl: null,
    coverImageUrl: null,
    galleryUrls: [],
    featured: true,
    views: 284,
  },
  {
    id: 'spiritbound-frontier',
    slug: 'spiritbound-frontier',
    title: 'Spiritbound Frontier',
    excerpt: {
      en: 'A farming simulation game with crop growth, inventory, construction, audio, physics and animation systems.',
      vi: 'Game mô phỏng nông trại với hệ thống cây trồng, inventory, xây dựng, âm thanh, vật lý và animation.',
    },
    content: {
      en: `## Overview\nA personal farming simulation project where the player grows crops, harvests resources and expands their land.\n\n## Engineering focus\n- Modular crop-growth and inventory systems.\n- Construction logic and reusable gameplay architecture.\n- Audio manager, Unity physics and animation.\n- Design patterns for scalable C# code.`,
      vi: `## Tổng quan\nDự án game mô phỏng nông trại cá nhân, nơi người chơi trồng cây, thu hoạch tài nguyên và mở rộng khu đất.\n\n## Trọng tâm kỹ thuật\n- Hệ thống crop-growth và inventory theo hướng module.\n- Logic xây dựng và kiến trúc gameplay tái sử dụng.\n- Audio Manager, Unity Physics và Animation.\n- Áp dụng Design Pattern để mã C# dễ mở rộng.`,
    },
    categories: ['Game'],
    technologies: ['Unity', 'C#', 'Game Design Patterns', 'Physics', 'Animation'],
    role: { en: 'Solo Developer', vi: 'Developer cá nhân' },
    startDate: '2026-01-01',
    endDate: '2026-03-01',
    teamSize: 1,
    status: { en: 'Completed milestone', vi: 'Hoàn thành milestone' },
    githubUrl: null,
    demoUrl: null,
    appStoreUrl: null,
    playStoreUrl: null,
    videoUrl: null,
    coverImageUrl: null,
    galleryUrls: [],
    featured: true,
    views: 193,
  },
  {
    id: 'harmony',
    slug: 'harmony-vr',
    title: 'Harmony',
    excerpt: {
      en: 'A VR supermarket simulation supporting diagnosis and cognitive training for daily activities.',
      vi: 'Mô phỏng siêu thị VR hỗ trợ chẩn đoán và luyện tập nhận thức cho các hoạt động hằng ngày.',
    },
    content: {
      en: `## Overview\nHarmony is a VR supermarket simulation developed in a research environment.\n\n## Responsibilities\n- Built immersive VR environments and interactive objects.\n- Used OpenXR and XR Interaction Toolkit.\n- Collaborated through Agile/Scrum.\n- Automated build workflows with Jenkins and GitHub.`,
      vi: `## Tổng quan\nHarmony là mô phỏng siêu thị VR được phát triển trong môi trường nghiên cứu.\n\n## Công việc\n- Xây dựng môi trường VR và vật thể tương tác.\n- Sử dụng OpenXR và XR Interaction Toolkit.\n- Phối hợp theo Agile/Scrum.\n- Tự động hóa build bằng Jenkins và GitHub.`,
    },
    categories: ['AR/VR', 'Research'],
    technologies: ['Unity 3D', 'C#', 'OpenXR', 'XR Interaction Toolkit', 'Jenkins', 'GitHub'],
    role: { en: 'Lead & Developer', vi: 'Lead & Developer' },
    startDate: '2025-09-01',
    endDate: null,
    teamSize: null,
    status: { en: 'In progress', vi: 'Đang phát triển' },
    githubUrl: null,
    demoUrl: null,
    appStoreUrl: null,
    playStoreUrl: null,
    videoUrl: null,
    coverImageUrl: null,
    galleryUrls: [],
    featured: true,
    views: 146,
  },
  {
    id: 'mini-3d-rendering-tool',
    slug: 'mini-3d-rendering-tool',
    title: 'Mini 3D Rendering Tool',
    excerpt: {
      en: 'A lightweight OpenGL renderer for OBJ models with orbit, zoom, pan, lighting and transformations.',
      vi: 'Công cụ render OpenGL gọn nhẹ cho mô hình OBJ với orbit, zoom, pan, lighting và transform.',
    },
    content: {
      en: `## Highlights\n- OpenGL rendering pipeline with shaders and lighting.\n- Orbit, zoom and pan camera controls.\n- OBJ mesh loading and transforms.\n- Phong / Blinn-Phong shading.\n- Performance optimization for smooth interaction.`,
      vi: `## Điểm nổi bật\n- Rendering pipeline OpenGL với shader và lighting.\n- Camera orbit, zoom và pan.\n- Load mesh OBJ và transform.\n- Phong / Blinn-Phong shading.\n- Tối ưu hiệu năng để thao tác mượt.`,
    },
    categories: ['Other'],
    technologies: ['C++', 'OpenGL', 'Shaders', '3D Graphics'],
    role: { en: 'Solo Developer', vi: 'Developer cá nhân' },
    startDate: '2026-03-01',
    endDate: null,
    teamSize: 1,
    status: { en: 'In progress', vi: 'Đang phát triển' },
    githubUrl: null,
    demoUrl: null,
    appStoreUrl: null,
    playStoreUrl: null,
    videoUrl: null,
    coverImageUrl: null,
    galleryUrls: [],
    featured: false,
    views: 88,
  },
  {
    id: 'pokemon-quiz',
    slug: 'pokemon-quiz',
    title: 'Pokemon Quiz',
    excerpt: {
      en: 'A quiz game combined with combat mechanics, random encounters, progression, shop and skins.',
      vi: 'Game quiz kết hợp combat, random encounter, progression, shop và skin.',
    },
    content: {
      en: `## Work completed\n- Rebalanced gameplay and fixed bugs.\n- Added Main Menu and Shop.\n- Extended combat loop with XP, money and skins.`,
      vi: `## Công việc đã làm\n- Cân bằng gameplay và sửa bug.\n- Thêm Main Menu và Shop.\n- Mở rộng vòng lặp combat với XP, tiền và skin.`,
    },
    categories: ['Game'],
    technologies: ['Unity', 'C#', 'GitHub'],
    role: { en: 'Lead & Developer', vi: 'Lead & Developer' },
    startDate: '2025-02-01',
    endDate: '2025-04-30',
    teamSize: null,
    status: { en: 'Completed', vi: 'Đã hoàn thành' },
    githubUrl: null,
    demoUrl: null,
    appStoreUrl: null,
    playStoreUrl: null,
    videoUrl: null,
    coverImageUrl: null,
    galleryUrls: [],
    featured: false,
    views: 101,
  },
  {
    id: 'mango',
    slug: 'mango-reading-platform',
    title: 'MANGO',
    excerpt: {
      en: 'A reading platform for comics and novels with authentication flows and responsive frontend pages.',
      vi: 'Nền tảng đọc truyện tranh và truyện chữ với luồng xác thực và giao diện responsive.',
    },
    content: {
      en: `## Contribution\nDesigned several interface screens and implemented the homepage, sign-in, sign-up and password-recovery frontend flows as part of a team project.`,
      vi: `## Đóng góp\nThiết kế một số màn hình và triển khai frontend cho trang chủ, đăng nhập, đăng ký và quên mật khẩu trong dự án nhóm.`,
    },
    categories: ['Web'],
    technologies: ['HTML', 'CSS', 'JavaScript', 'Frontend'],
    role: { en: 'Frontend Developer', vi: 'Frontend Developer' },
    startDate: '2024-10-01',
    endDate: '2024-12-31',
    teamSize: null,
    status: { en: 'Completed', vi: 'Đã hoàn thành' },
    githubUrl: null,
    demoUrl: null,
    appStoreUrl: null,
    playStoreUrl: null,
    videoUrl: null,
    coverImageUrl: null,
    galleryUrls: [],
    featured: false,
    views: 74,
  },
  {
    id: 'print-shop',
    slug: 'print-shop',
    title: 'Print Shop',
    excerpt: {
      en: 'A student print-ordering website with configurable print options and account pages.',
      vi: 'Website đặt đơn in cho sinh viên với tùy chọn in và trang thông tin người dùng.',
    },
    content: {
      en: `Implemented frontend interfaces for the homepage, about page, authentication and user profile in a team project.`,
      vi: `Triển khai frontend cho trang chủ, giới thiệu, xác thực và trang thông tin người dùng trong dự án nhóm.`,
    },
    categories: ['Web'],
    technologies: ['HTML', 'CSS', 'JavaScript', 'Frontend'],
    role: { en: 'Frontend Developer', vi: 'Frontend Developer' },
    startDate: '2024-10-01',
    endDate: '2024-12-31',
    teamSize: null,
    status: { en: 'Completed', vi: 'Đã hoàn thành' },
    githubUrl: null,
    demoUrl: null,
    appStoreUrl: null,
    playStoreUrl: null,
    videoUrl: null,
    coverImageUrl: null,
    galleryUrls: [],
    featured: false,
    views: 62,
  },
]

export const experiences: Experience[] = [
  {
    id: 'hcmut-ura-harmony',
    company: 'Ho Chi Minh City University of Technology — URA Research Group',
    position: { en: 'VR Developer — Harmony', vi: 'VR Developer — Harmony' },
    location: 'Ho Chi Minh City',
    startDate: '2025-09-01',
    endDate: null,
    current: true,
    description: {
      en: 'Developing a VR supermarket simulation that supports diagnosis and cognitive training for daily activities.',
      vi: 'Phát triển mô phỏng siêu thị VR hỗ trợ chẩn đoán và luyện tập nhận thức cho các hoạt động hằng ngày.',
    },
    responsibilities: [
      { en: 'Develop immersive VR environments and interactive objects.', vi: 'Phát triển môi trường VR và các vật thể tương tác.' },
      { en: 'Collaborate in Agile/Scrum with sprint planning and task tracking.', vi: 'Phối hợp theo Agile/Scrum với sprint planning và task tracking.' },
      { en: 'Automate build processes with Jenkins and GitHub.', vi: 'Tự động hóa quy trình build bằng Jenkins và GitHub.' },
    ],
    technologies: ['Unity', 'C#', 'OpenXR', 'XR Interaction Toolkit', 'Jenkins'],
    logoUrl: null,
    companyUrl: null,
  },
]

export const education: Education[] = [
  {
    id: 'hcmut',
    institution: 'Ho Chi Minh City University of Technology',
    degree: { en: 'Bachelor of Computer Science', vi: 'Cử nhân Khoa học Máy tính' },
    field: { en: 'Computer Science — Japan-oriented program', vi: 'Khoa học Máy tính — Định hướng Nhật Bản' },
    startDate: '2022-10-01',
    endDate: null,
    current: true,
    gpa: '3.2 / 4.0',
    description: { en: 'Computer Science student focused on interactive systems, game development and research.', vi: 'Sinh viên Khoa học Máy tính tập trung vào hệ thống tương tác, phát triển game và nghiên cứu.' },
    thesis: null,
    logoUrl: null,
  },
  {
    id: 'green-academy',
    institution: 'Green Academy',
    degree: { en: 'Game Developer Course', vi: 'Khóa học Game Developer' },
    field: { en: 'Game Development', vi: 'Phát triển Game' },
    startDate: '2025-11-01',
    endDate: null,
    current: true,
    gpa: '10 / 10',
    description: null,
    thesis: null,
    logoUrl: null,
  },
]

export const skills: Skill[] = [
  { id: 'unity', name: 'Unity', category: 'Game Development', sortOrder: 1 },
  { id: 'csharp', name: 'C#', category: 'Programming Languages', sortOrder: 2 },
  { id: 'cpp', name: 'C/C++', category: 'Programming Languages', sortOrder: 3 },
  { id: 'ts', name: 'JavaScript / TypeScript', category: 'Programming Languages', sortOrder: 4 },
  { id: 'python', name: 'Python', category: 'Programming Languages', sortOrder: 5 },
  { id: 'php', name: 'PHP', category: 'Programming Languages', sortOrder: 6 },
  { id: 'ar-foundation', name: 'AR Foundation', category: 'AR/VR', sortOrder: 7 },
  { id: 'vuforia', name: 'Vuforia', category: 'AR/VR', sortOrder: 8 },
  { id: 'openxr', name: 'OpenXR', category: 'AR/VR', sortOrder: 9 },
  { id: 'xr-toolkit', name: 'XR Interaction Toolkit', category: 'AR/VR', sortOrder: 10 },
  { id: 'figma', name: 'Figma', category: 'Tools', sortOrder: 11 },
  { id: 'git', name: 'Git / GitHub / GitLab', category: 'Tools', sortOrder: 12 },
  { id: 'jenkins', name: 'Jenkins', category: 'DevOps', sortOrder: 13 },
  { id: 'supabase', name: 'Supabase', category: 'Database', sortOrder: 14 },
]

export const certificates: Certificate[] = [
  {
    id: 'jp-n4',
    title: { en: 'Japanese N4 Completion Certificate', vi: 'Chứng nhận hoàn thành tiếng Nhật N4' },
    issuer: 'Kohi Japanese Language',
    issueDate: null,
    credentialId: null,
    credentialUrl: null,
    imageUrl: null,
    pdfUrl: null,
  },
  {
    id: 'api-design',
    title: { en: 'Efficient API Design with Node.js', vi: 'Efficient API Design with Node.js' },
    issuer: 'SORIMACHI Vietnam',
    issueDate: null,
    credentialId: null,
    credentialUrl: null,
    imageUrl: null,
    pdfUrl: null,
  },
  {
    id: 'oisp-scholarship',
    title: { en: 'OISP Scholarship Certificates', vi: 'Chứng nhận học bổng OISP' },
    issuer: 'HCMUT OISP',
    issueDate: null,
    credentialId: null,
    credentialUrl: null,
    imageUrl: null,
    pdfUrl: null,
  },
]

export const awards: Award[] = [
  {
    id: 'student-5-merits',
    title: { en: 'Student of 5 Merits — 2024–2025', vi: 'Sinh viên 5 tốt — 2024–2025' },
    issuer: 'Ho Chi Minh City University of Technology',
    awardDate: '2025-01-01',
    description: null,
    certificateIds: [],
  },
  {
    id: 'excellent-student',
    title: { en: 'Comprehensive Excellent Student — 2024–2025', vi: 'Sinh viên Giỏi toàn phần — 2024–2025' },
    issuer: 'Ho Chi Minh City University of Technology',
    awardDate: '2025-01-01',
    description: null,
    certificateIds: [],
  },
  {
    id: 'innovation-top40',
    title: { en: 'Top 40 Bach Khoa Innovation', vi: 'Top 40 Bách Khoa Innovation' },
    issuer: 'Ho Chi Minh City University of Technology',
    awardDate: '2025-01-01',
    description: null,
    certificateIds: [],
  },
  {
    id: 'community-top36',
    title: { en: 'Top 36 Excellent Community Projects', vi: 'Top 36 Excellent Community Projects' },
    issuer: null,
    awardDate: null,
    description: null,
    certificateIds: [],
  },
]

export const research: ResearchItem[] = [
  {
    id: 'agentic-ar-research',
    title: { en: 'Agentic AR navigation research', vi: 'Nghiên cứu dẫn đường Agentic AR' },
    venue: 'Computers & Graphics (Elsevier) — SCIE',
    status: { en: 'In development', vi: 'Đang phát triển' },
    description: {
      en: 'Research direction around AR-assisted navigation and indoor/outdoor handoff.',
      vi: 'Hướng nghiên cứu về dẫn đường hỗ trợ AR và chuyển giao indoor/outdoor.',
    },
    projectId: 'agentic-ar',
    url: null,
  },
]

export const languages: LanguageItem[] = [
  {
    id: 'japanese',
    name: { en: 'Japanese', vi: 'Tiếng Nhật' },
    level: { en: 'N4 certified', vi: 'Chứng nhận N4' },
  },
]

export const blogPosts: BlogPost[] = [
  {
    id: 'welcome',
    slug: 'welcome-to-my-portfolio',
    title: { en: 'Welcome to my portfolio', vi: 'Chào mừng đến với portfolio của mình' },
    excerpt: {
      en: 'A small note about what I am building, learning and documenting here.',
      vi: 'Một lời giới thiệu ngắn về những gì mình đang xây dựng, học hỏi và ghi lại ở đây.',
    },
    content: {
      en: `# Hello 👋\n\nThis space is where I share projects, technical notes, research experiments and lessons learned while building games and interactive experiences.\n\n> This starter post can be replaced from the Admin dashboard once Supabase is connected.`,
      vi: `# Xin chào 👋\n\nĐây là nơi mình chia sẻ dự án, ghi chú kỹ thuật, thử nghiệm nghiên cứu và những bài học trong quá trình làm game và các trải nghiệm tương tác.\n\n> Bài viết mẫu này có thể được thay trực tiếp từ trang Admin sau khi kết nối Supabase.`,
    },
    tags: ['Portfolio', 'Unity', 'Learning'],
    coverImageUrl: null,
    featured: true,
    publishedAt: '2026-09-04T00:00:00.000Z',
    views: 42,
  },
]
